feat: `umami.identity` support
jaseeey/vue-umami-plugin pull request #3
Opened 2024-11-12 20:28 UTC by ThatOneCalculator

refs:

- https://umami.is/docs/tracker-functions#session-data
- https://umami.is/docs/sessions
- https://github.com/umami-software/umami/discussions/2934

2024-11-26 22:16 UTC, ThatOneCalculator commented
@jaseeey would love a review on this as well, no rush :)

2024-11-26 23:28 UTC, jaseeey commented
> @jaseeey would love a review on this as well, no rush :)

Yep, no problems, I will get to this one soon too and group the changes in the same version.

2025-01-06 17:57 UTC, ThatOneCalculator commented
@jaseeey re-requesting review :)

2025-01-09 13:01 UTC, jaseeey requested changes
Just two things to modify:

* There is a change in the README.md which modifies the indentation within the Javascript code block to be inconsistent with the rest.
* There appears to be a bun.lockb file included? I don't use bun, can it simply use the package-lock.json?

2025-01-09 13:01 UTC, jaseeey commented on README.md
> -    websiteID: 'YOUR_UMAMI_WEBSITE_ID',
Lines 44-46 seem to have indentation adjusted from 4 spaces to 2 spaces.

2025-01-09 13:01 UTC, jaseeey commented on src/index.ts
> +import type { RouteLocationNormalized, Router } from 'vue-router';
I don't use TypeScript a lot, didn't know you could do this :) cool.

2025-01-09 18:59 UTC, ThatOneCalculator commented on README.md
> -    websiteID: 'YOUR_UMAMI_WEBSITE_ID',
Sorry about that – my IDE automatically formatted that

2025-01-09 19:09 UTC, ThatOneCalculator commented
@jaseeey sorry about the multiple commits, between saving and formatting my IDE was not trying to let me push the readme unformatted ^^;

Should be all good now!

2025-01-23 12:11 UTC, jaseeey approved these changes
Looks good to me. Apologies for the massive delay in getting it merged in, been working on getting a project online :)

2025-01-23 12:13 UTC, merged